services:
  # 🔊 Ultra-fast echo server
  echo:
    build:
      context: ../
    volumes:
      - ./echo.yml:/anygate.yml
    ports:
      - "8000:80"

  # 🌀 AnyGate
  anygate:
    build:
      context: ../
    volumes:
      - ./anygate.yml:/anygate.yml
      - ./:/a/
    ports:
      - "8001:80"
    depends_on:
      - echo

  # ⚙️ HAProxy
  haproxy:
    image: haproxy:3.1
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8002:80"
    depends_on:
      - echo

   # 📦 NGINX
  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8003:80"
    depends_on:
      - echo

  # 📦 NGINX подтюненный
  nginx-dark:
    image: nginx:1.27
    volumes:
      - ./nginx-dark.conf:/etc/nginx/nginx.conf
    ports:
      - "8004:80"
    depends_on:
      - echo

  # 🧪 Benchmark (используй вручную)
  wrk:
    image: williamyeh/wrk
    entrypoint: ["/bin/sh"]
    tty: true
    # entrypoint: ["sh", "-c", "tail -f /dev/null"]  # запускаем в фоне, запускай команды руками
    
  # 🧪 Benchmark (используй вручную)
  ab:
    image: jordi/ab
    entrypoint: ["/bin/sh"]
    tty: true