# Nginx тут реально как будто в шлёпанцах на олимпиаде. По дефолту Nginx не заточен на хайперформанс. Вот как мы его апгрейдим до режима "я пришёл побеждать":
worker_processes auto;

events {
    worker_connections 4096;  # 💪 больше коннектов
    use epoll;                # ⚡ Linux-style I/O
    multi_accept on;
}

http {
    access_log off;           # 📴 логам — отбой
    error_log /dev/null crit; # 🙈 только серьёзное

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 5;
    # keepalive_requests 100000; # 💪 Никаких лишних разрывов!

    server {
        listen 80;
        location / {
            proxy_pass http://echo:80;
        }
    }
}